// AGENTS.md section 9 is authoritative. Keep this literal and the JSON mirror in sync.
// Copied guard imports this constant for janitor exception condition 6.
// One entry per line, including a trailing comma on the final entry; tested by the fence suite.
export const FENCE_GLOBS = [
  ".github/workflows/**",
  ".githooks/**",
  "scripts/flywheel-guard.mjs",
  "scripts/flywheel-fence.mjs",
  "scripts/install-flywheel-hooks.mjs",
  "scripts/review-sweep.mjs",
  "test/flywheel-guard.test.mjs",
  "test/flywheel-fence-globs.test.mjs",
  "test/install-flywheel-hooks.test.mjs",
  "test/review-sweep.test.mjs",
  "flywheel.guard.json",
  ".nvmrc",
  "AGENTS.md",
  "Cargo.toml",
  "Cargo.lock",
  "crates/*/Cargo.toml",
  "crates/*/Cargo.lock",
  "crates/*/fuzz/Cargo.toml",
  "crates/*/fuzz/Cargo.lock",
  "experimental/*/Cargo.toml",
  "vendor/*/Cargo.toml",
  "rust-toolchain.toml",
  ".cargo/**",
  ".config/nextest.toml",
  "Dockerfile",
  "Dockerfile.release",
  "install.sh",
  "install.ps1",
  "install-local.sh",
  "crates/mcp-agent-mail-core/src/config.rs",
  "crates/mcp-agent-mail-core/src/mcp_config.rs",
  "crates/mcp-agent-mail-db/src/**",
  "crates/mcp-agent-mail-storage/src/**",
  "crates/mcp-agent-mail-guard/src/**",
  "crates/mcp-agent-mail-cli/src/doctor/**",
];
